services:
  api:
    build: .
    ports:
      - '8082:8082'
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/build
    networks:
      - default
      - sleeved-network

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - '3307:3306'
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p${MYSQL_ROOT_PASSWORD}',
          '--silent',
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - default
      - looter-network
    container_name: sleeved-db

networks:
  default:
  sleeved-network:
    external: true
  looter-network:
    external: true

volumes:
  db_data:
