services:
  atlas:
    build: .
    ports:
      - '8082:8082'
    depends_on:
      - sleeved_db
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/build

  sleeved_db:
    image: mysql:8
    ports:
      - '3307:3306'
    env_file:
      - .env
    volumes:
      - sleeved_db-data:/var/lib/mysql

volumes:
  sleeved_db-data:
