version: '3'

services:
  app:
    build: .
    ports:
      - '3333:3333'
    depends_on:
      - mysql
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/build

  mysql:
    image: mysql:8
    ports:
      - '3307:3307'
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
