services:
  api:
    build: .
    ports:
      - '8082:8082'
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/build

  mysql:
    image: mysql:8
    ports:
      - '3307:3306'
    env_file:
      - .env
    volumes:
      - sleeved_db-data:/var/lib/mysql
      - ./sleeved_db_v4.sql:/docker-entrypoint-initdb.d/sleeved_db_v4.sql
    healthcheck:
      test: ['CMD-SHELL', "mysql -h localhost -u root -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1;'"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  sleeved_db-data:
