services:
  api:
    build: .
    ports:
      - '8082:8082'
    depends_on:
      - mysql
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/build

  mysql:
    image: mysql:8
    ports:
      - '3307:3306'
    env_file:
      - .env
    volumes:
      - sleeved_db-data:/var/lib/mysql
      - ./sleeved_db_v4.sql:/docker-entrypoint-initdb.d/sleeved_db_v4.sql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  sleeved_db-data:
