services:
  api:
    build: .
    ports:
      - '8082:8082'
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/build
    networks:
      - default
      - sleeved-network

  mysql:
    image: mysql:8
    ports:
      - '3307:3306'
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./sleeved_db_dump.sql:/docker-entrypoint-initdb.d/sleeved_db_dump.sql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 30s
      retries: 10
    networks:
      - default

networks:
  default:
  sleeved-network:
    external: true

volumes:
  db_data:
