services:
  api-test:
    build: .
    ports:
      - '8082:8082'
    depends_on:
      mysql-test:
        condition: service_healthy
    env_file:
      - .env.test
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/build
    networks:
      - test-network

  mysql-test:
    image: mysql:8.0
    restart: always
    ports:
      - '3307:3306'
    env_file:
      - .env.test
    volumes:
      - db_test_data:/var/lib/mysql
      - ./sleeved_db_structure_dump.sql:/docker-entrypoint-initdb.d/sleeved_db_structure_dump.sql
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p${MYSQL_ROOT_PASSWORD}',
          '--silent',
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - test-network
    container_name: sleeved-db-test

networks:
  test-network:

volumes:
  db_test_data:
