name: Atlas CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Check Prettier formatting
        run: npm run format:check

      - name: TypeScript check
        run: npm run typecheck

  test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Copy .env
        run: cp .env.test .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create networks
        run: |
          docker network create sleeved-network
          docker network create looter-network

      - name: Build and start containers
        run: docker compose up -d --build

      - name: Import database from dump file
        run: |
          source .env && \
          echo "🔄 Démarrage de l'importation..." && \
          docker compose exec -T mysql mysql -uroot -p"$MYSQL_ROOT_PASSWORD" -h 127.0.0.1 $DB_DATABASE < ./sleeved_db_dump.sql && \
          echo "✅ Importation terminée avec succès !"

      - name: Wait before migrations
        run: sleep 10

      - name: Run migrations
        run: docker compose exec -T api node ace migration:run

      - name: Run tests
        run: docker compose exec -T api npm test

      - name: Show logs in case of failure
        if: failure()
        run: docker compose logs

      - name: Stop containers
        if: always()
        run: docker compose down -v
