name: Atlas CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Check Prettier formatting
        run: npm run format:check

      - name: TypeScript check
        run: npm run typecheck

  test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start test containers
        run: docker-compose -f docker-compose.test.yml up -d --build

      - name: Wait before dump
        run: sleep 20

      - name: Run migrations
        run: docker-compose -f docker-compose.test.yml exec api-test node ace migration:run

      - name: Run tests
        run: docker-compose -f docker-compose.test.yml exec api-test npm test

      - name: Show logs in case of failure
        if: failure()
        run: docker-compose -f docker-compose.test.yml logs

      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose.test.yml down -v
